[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "answer mixture scheme shrug token hundred goddess remain into uncle street almost place scale inherit lake fly task design buzz huge arrange fortune renew "